---
title: "LAB 26 (MD)"
author: "AnaGSanjuanM"
date: "2023-02-23"
output: html_document
---

---------------LABORATORIO 26---------------------

Tidy data - datos ordenados - Parte 2


Cargar paquete tidyverse

```{r}
library(tidyverse)
```


Cargar paquete de datos
```{r}
library("datos")
```

Cargar las tablas del paquete de datos como tibble
```{r}
datos::tabla1
datos::tabla2
datos::tabla3
datos::tabla4a
datos::tabla4b
```

Se obtienen los dataframe de las tablas
```{r}
df1 <- data_frame(tabla1)
df2 <- data_frame(tabla2)
df3 <- data_frame(tabla3)
df4a <- data_frame(tabla4a)
df4b <- data_frame(tabla4b)
```

Exportar los dataframes originales
```{r}
write.csv(df1,file="df1.csv")
write.csv(df2,file="df2.csv")
write.csv(df3,file="df3.csv")
write.csv(df4a,file="df4a.csv")
write.csv(df4b,file="df4b.csv")
```

Ordenar datos con la tabla4a (PIVOTAR). Se añade el operador pipe %>% (presionando ctrl Shift M).

Se genera objeto llamado t4a_PIVOTANTE (será una tabla ordenada), para pivotear a lo largo (pivot_longer)

Las columnas están dadas por los años y se reemplazará el nombre por anio en los que englobará los dos momentos en el tiempo.

Los valores se tomarán como casos.
```{r}
t4a_PIVOTANTE = tabla4a %>%
  pivot_longer(cols=c("1999", "2000"), names_to="anio", values_to = "casos")
```

Para visualizar
```{r}
t4a_PIVOTANTE
```

1. Pivotar tabla 4b

Ordenar datos con la tabla4b (PIVOTAR). Se añade el operador pipe %>% (presionando ctrl Shift M)

Se genera objeto llamado t4b_PIVOTANTE (será una tabla ordenada), para pivotear a lo largo (pivot_longer). Las columnas están dadas por los años y se reemplazará el nombre por anio en los que englobará los dos momentos en el tiempo.Los valores se tomarán como poblacion.
```{r}
t4b_PIVOTANTE = tabla4b %>%
  pivot_longer(cols=c("1999", "2000"), names_to="anio", values_to = "poblacion")
```

Para visualizar
```{r}
t4b_PIVOTANTE
```

2. Combinar las versiones ordenadas de tabla4a y tabla4b (ocupando dplyr)

Generar objeto llamado unión de las tablas 4 (a y b) que será igual a una unión a partir de la izquierda (left_join)

Se unen la t4a_PIVOTANTE y la t4b_PIVOTANTE
```{r}
union_t4 = left_join(t4a_PIVOTANTE, t4b_PIVOTANTE)
```

Para visualizar
```{r}
union_t4
```

Exportar resultados tabla4a + tabla4b (ordenada)
```{r}
write.csv(union_t4, file="union_t4.csv")
```

3. DATOS ANCHOS CON TABLA 2

Para visualizar
```{r}
df2
```

Es una base de datos larga, por lo que debemos hacerla ancha

Pivotar tabla 2 "A LO ANCHO"

Se crea objeto llamdo t2_ancha. Será igual a la tabla2 original pero con filtro (operador pipe)

Como el pivotaje será a lo ancho, se ocupará pivot_wider.

Se establecen nombres (names_from) que será igual a tipo. Values_from será igual a cuenta
```{r}
t2_ancha = tabla2 %>% 
  pivot_wider(names_from = tipo, values_from = cuenta)
```

Para vsisualizar
```{r}
t2_ancha
```

Exportar la tabla ordenada recien creada
```{r}
write.csv(t2_ancha, file = "t2_ancha.csv")
```


------------------------FIN DE LABORATORIO 26----------------